### ISSUE TITLE
Not an actual tool

### ISSUE THREAD

**Issue by Eruptsy** [RetroPackets/Xurma-Dox#2]

**Comment by RetroPackets** [comment]
It actually is a tool. To get it to work complete the human verification as
instructed

**Comment by Eruptsy** [comment]
The script will not work. As you can see in functions option1,2 and 3 are running other python script that are on ur system. If i downloaded this tool and ran it. It will cause errors indicating there are no files or directory called xurma-dox-email.py, xurma-dox-ip.py, xurma-dox-phone.py. And you didnt even upload those files either. There is legit no point in this repo. If you want me to test it out to give you LIVE proof that this doesn't unless its on your system where you have the other files than i'll be more than glad you to show you proof

**Comment by RetroPackets** [comment]
Hey idiot the damn files are in the src folder I know what I'm doing fuck
head

**Comment by RetroPackets** [comment]
User complained about it not being an actual tool and that if he downloaded it then it would say the files in the sec folder ate missing witch is completely wrong because I have show cased the tool on this youtube video here. https://youtu.be/Ixzz7YMYeP8. Dont complain about stuf that isnt an actual issue

**Comment by Eruptsy** [comment]
Why do you keep deleting my comment. Anybody who knows python will be able to know this don't work without even testing it. You've already been exposed more than 5 times on IG within the last 2/3 days. You do have to hide comments. The next time you delete my comment. I will fork this repo to put out a message on the README.md
